version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: meetingbot-db
    environment:
      POSTGRES_USER: meetingbot
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: meetingbotpoc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [meetingbot]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.be
    container_name: meetingbot-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
      - bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [meetingbot]

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: meetingbot-bot
    entrypoint: ["true"]
    networks: [meetingbot]

volumes:
  pgdata:

networks:
  meetingbot:
    name: meetingbot-net
